### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by athas** [filecoin-project/phase2-attestations#2]
The Rust code depends on `openssl-sys`, which requires Perl to build.

**Comment by DrPeterVanNostrand** [comment]
Were you on Ubuntu 18, or a different OS?

**Comment by athas** [comment]
I was on NixOS.  Ubuntu probably has Perl in its base system.

**Comment by vmx** [comment]
There are way so many distros out there, we sadly cannot support them all, hence I'm closing this issue. Though this issue will be a good reference if someone hits the same problem, thanks for reporting!
